# Generated by Django 4.1.3 on 2024-10-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
