# Generated by Django 4.1.3 on 2024-10-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
